document.getElementById("ig-button").addEventListener("click", function() {
    window.open('https://www.instagram.com/leogranjadev/', '_blank');
});
document.getElementById("lkdIn-button").addEventListener("click", function() {
    window.open('https://www.linkedin.com/in/leonardo-fonseca-97565326b/', '_blank');
});
document.getElementById("wpp-button").addEventListener("click", function() {
    window.open('https://wa.me/5512997772296', '_blank');
});


