document.getElementById("button-projetos").addEventListener("click", function() {
    window.location.href = "Pages/projectsPage.html";    
});

document.getElementById("button-projetos2").addEventListener("click", function() {
    window.location.href = "Pages/projectsPage.html";    
});

document.getElementById("heaeder-button-sobreMim").addEventListener("click", function() {
    //window.open('URL PAGINA Sobre mim', '_blank');
});

document.getElementById("button-SobreMim").addEventListener("click", function() {
    //window.open('URL PAGINA Sobre mim', '_blank');
});

document.getElementById("button-Contato").addEventListener("click", function() {
    //window.open('URL PAGINA Contato', '_blank');
});
