document.getElementById("heaeder-button-Projetos").addEventListener("click", function() {
    //window.open('URL PAGINA PROJETOS', '_blank');
});

document.getElementById("heaeder-button-sobreMim").addEventListener("click", function() {
    //window.open('URL PAGINA Sobre mim', '_blank');
});

document.getElementById("button-SobreMim").addEventListener("click", function() {
    //window.open('URL PAGINA Sobre mim', '_blank');
});

document.getElementById("button-Projetos").addEventListener("click", function() {
    //window.open('URL PAGINA PROJETOS', '_blank');
});

document.getElementById("button-Contato").addEventListener("click", function() {
    //window.open('URL PAGINA Contato', '_blank');
});
