function buttonMainPage(){
    window.location.href = "https://my-web-page-react.vercel.app";    
}

function buttonProjetos(){
    window.location.href = "https://my-web-page-react.vercel.app";    
}

function buttonSobreMim(){    
    window.location.href = "https://my-web-page-react.vercel.app";
}

function buttonContato(){
    window.open('https://wa.me/5512997772296', '_blank');
}

function indexEnProj(){
    window.location.href = "https://my-web-page-react.vercel.app";    
}

function indexEnSobreMim(){
    window.location.href = "https://my-web-page-react.vercel.app";
}

