function buttonMainPage(){
    window.location.href = "../index.html";    
}

function buttonProjetos(){
    window.location.href = "projects.html";    
}

function buttonSobreMim(){    
    window.location.href = "sobreMim.html";
}

function buttonContato(){
    window.open('https://wa.me/5512997772296', '_blank');
}

function indexEnProj(){
    window.location.href = "../../English/Pages/projectsEn.html";
}

function indexEnSobreMim(){
    window.location.href = "../../English/Pages/SobreMimEn.html";
}

