document.getElementById("ig-button").addEventListener("click", function() {
    window.open('https://www.instagram.com/leogranjadev/', '_blank');
});
document.getElementById("lkdIn-button").addEventListener("click", function() {
    window.open('https://www.linkedin.com/in/leonardo-fonseca-97565326b/', '_blank');
});
document.getElementById("wpp-button").addEventListener("click", function() {
    window.open('https://wa.me/5512997772296', '_blank');
});
document.getElementById("github-button").addEventListener("click", function() {
    window.open('https://github.com/SrJasper', '_blank');
});
document.getElementById("CV-button").addEventListener("click", function() {
    window.open(
        "https://drive.google.com/drive/folders/1jyQVl4xYsjufltCrIHQugWa3Qd6nuwzv?usp=sharing",
        "_blank"
      );
});


