function buttonMainPage(){
    window.location.href = "../indexEn.html";    
}

function buttonProjetos(){
    window.location.href = "projectsEn.html";    
}

function buttonSobreMim(){    
    window.location.href = "sobreMimEn.html";
}

function buttonContato(){
    window.open('https://wa.me/5512997772296', '_blank');
}

function indexBraProj(){
    window.location.href = "../../Pages/projects.html";
}

function indexBraSobreMim(){
    window.location.href = "../../Pages/SobreMim.html";
}
