function buttonMainPage(){
    window.location.href = "https://leo-fonseca.vercel.app";    
}

function buttonProjetos(){
    window.location.href = "https://leo-fonseca.vercel.app/projects";    
}

function buttonSobreMim(){    
    window.location.href = "https://leo-fonseca.vercel.app/me";
}

function buttonContato(){
    window.open('https://wa.me/5512997772296', '_blank');
}

function indexEnProj(){
    window.location.href = "https://leo-fonseca.vercel.app/projects";    
}

function indexEnSobreMim(){
    window.location.href = "https://leo-fonseca.vercel.app/me";
}

