function Calc(){
    window.open("https://leoscalcproject.netlify.app/", "StockPage");
}

function TM(){
    window.open("https://leostaskmanager.netlify.app/", "StockPage");
}

function JeT(){
    window.open("https://github.com/SrJasper/Jet/releases/tag/JeT", "StockPage");
}

function Store(){
    window.open("https://loja.leosstore.shop/listar/todos", "StockPage");
    
}

function Stock() {
    window.open("https://stock-front-react.vercel.app", "StockPage");
}
